### ISSUE TITLE
Merge your txt files into README 

### ISSUE THREAD

**Issue by Pradhyo** [Madhu317/Wrangle-Open-Street-Maps-Chennai#1]
README is a Markdown file, [here](https://help.github.com/articles/basic-writing-and-formatting-syntax/) is a useful link

**Comment by madhushrirajagopal** [comment]
Thank you, that was helpful. [README](https://github.com/Madhu317/Wrangle-Open-Street-Maps-Chennai/blob/master/README.md) updated.

**Comment by Pradhyo** [comment]
@Madhu317 do you still need the .txt files?
